JNG-4516 Release operation utils
BlackBeltTechnology/judo-operation-utils pull request #24
Opened 2023-03-02 11:05 UTC by gaborflorian

2023-03-02 11:36 UTC, noherczeg approved these changes

2023-03-02 12:48 UTC, bencegelei approved these changes

2023-03-02 14:35 UTC, fmagnucz requested changes

2023-03-02 14:35 UTC, fmagnucz commented on .github/CIFLOW.adoc
> +* 3rd number in version of hotfix/ branches is increased when started (that are applied on both release and master branches)
I think it could be "4th"

2023-03-02 20:03 UTC, robertcsakany approved these changes

2023-03-06 11:20 UTC, bencegelei approved these changes

2023-03-09 11:54 UTC, gaborflorian commented on .github/CIFLOW.adoc
> +* 3rd number in version of hotfix/ branches is increased when started (that are applied on both release and master branches)
It will be resolve in the future

2023-03-09 11:54 UTC, merged